### ISSUE TITLE
Security - Remove CLI options method of passing Azure credentials

### ISSUE THREAD

**Issue by paegun** [julienstroheker/dcos-autoscaler#1]
Please remove the CLI options method of passing Azure credentials. 

The Azure CLI, AWS CLI, and boto client all follow the security best practice of not passing credentials via the command line, see the following:
https://docs.microsoft.com/en-us/azure/xplat-cli-connect
http://boto3.readthedocs.io/en/latest/guide/configuration.html

The MySQL docs provide the rationale, see the following (specifically the paragraph starting w/ "This is convenient but _insecure_ ....") : 
https://dev.mysql.com/doc/refman/5.7/en/password-security-user.html

**Comment by julienstroheker** [comment]
Yep, I will move those credentials to the ENV variables.

**Comment by julienstroheker** [comment]
@paegun I just pushed an update on the code to allow the ENV variable in the container.
Any feedbacks are welcome :)

Thanks

**Comment by paegun** [comment]
@julienstroheker +1 for adding the ability to specify Azure credentials and other such sensitive data via environment in https://github.com/julienstroheker/dcos-autoscaler/commit/99609e5e3c00a866aa692018112c9ca5aae66a7e AND another +1 for updating the docs and README to use the environment method.

-0.001 for not removing the ability to specify the sensitive data via the command line, so ... great! Thank you
